### ISSUE TITLE
[BUG] (ABL Menu has disappeared)

### ISSUE THREAD

**Issue by z00mantwo** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1155]
### Description

Compiled latest version as 10/5/20 with 

default_envs = BIGTREE_TFT35_E3_V3_0

ABL menu has disappeared from "Movement" menu. Appeared on previous version compiled from newest code 9/23/20. Also get following compile errors:

In file included from C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Inc/stm32f1xx_hal_def.h:46:0,
                 from C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Inc/stm32f1xx_hal_rcc.h:45,
                 from C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Inc/stm32f1xx_hal_conf.h:234,
                 from C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Inc/stm32f1xx_hal.h:46,
                 from C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_can.c:161:
C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_can.c: In function 'HAL_CAN_GetTxTimestamp':
C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\CMSIS\Device\ST\STM32F1xx\Include/stm32f1xx.h:210:32: warning: implicit declaration of function '__CLZ' [-Wimplicit-function-declaration]
 #define POSITION_VAL(VAL)     (__CLZ(__RBIT(VAL)))
                                ^
C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_can.c:1097:23: note: 
in expansion of macro 'POSITION_VAL'
     transmitmailbox = POSITION_VAL(TxMailbox);
                       ^~~~~~~~~~~~

In file included from C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Inc/stm32f1xx_hal_def.h:46:0,
                 from C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Inc/stm32f1xx_hal_rcc.h:45,
                 from C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Inc/stm32f1xx_hal_conf.h:234,
                 from C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Inc/stm32f1xx_hal.h:46,
                 from C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_pwr.c:43:
C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_pwr.c: In function 'HAL_PWR_EnableWakeUpPin':
C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\CMSIS\Device\ST\STM32F1xx\Include/stm32f1xx.h:210:32: warning: implicit declaration of function '__CLZ' [-Wimplicit-function-declaration]
 #define POSITION_VAL(VAL)     (__CLZ(__RBIT(VAL)))
                                ^
C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_pwr.c:114:92: note: in expansion of macro 'POSITION_VAL'
 #define CSR_EWUP_BB(VAL)         ((uint32_t)(PERIPH_BB_BASE + (PWR_CSR_OFFSET_BB * 32U) + (POSITION_VAL(VAL) * 4U)))
                                                                                            ^~~~~~~~~~~~
C:\Users\Garey\.platformio\packages\framework-stm32cube\f1\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_pwr.c:403:22: note: in expansion of macro 'CSR_EWUP_BB'
   *(__IO uint32_t *) CSR_EWUP_BB(WakeUpPinx) = (uint32_t)ENABLE;
                      ^~~~~~~~~~~

**Comment by traffic-light** [comment]
I think it's moved. @digant73 you made some changes here.

**Comment by z00mantwo** [comment]
It isn't moved. Went through every menu. It's just gone. I'm guessing the detection method has broken.

**Comment by digant73** [comment]
as far as I know that kind of bug was found and fixed in #1138.
In the last code the BL menu (in move menu) is shown if a BL type (ABL, UBL, MBL) is detected during M503 and M115. For some Marlin FW, the BL type was not detected so no BL menu was shown.
As I workaround, from the terminal menu type M503. After that you should see the BL menu

**Comment by z00mantwo** [comment]
Also note that the notifications that ABL is on and fade height never go off like in the old version. If I go to the machine settings and turn on ABL manually then those notifications popup. The ABL menu still does not show up. I believe the issue may be related to this. ABL is on but the new version is not detecting it. M420 returns:

Send: M420
Recv: echo:Bed Leveling ON
Recv: echo:Fade Height 2.00
Recv: ok

So the printer has ABL turned on. The new version never seems to detect this.

**Comment by z00mantwo** [comment]
Also if I go back to the 26.1 version everything works and the alerts on ABL and fade height show up as soon as I turn on the printer and the ABL menu is there.

**Comment by digant73** [comment]
M420 is to activate/deativate the use of ABL not to detect what kind of BL is provided by Marlin FW (ABL, UBL, MBL etc...).
Your problem should be fixed in #1138.

**Comment by z00mantwo** [comment]
I'm on the "master" as of 3 days ago. So I believe that should include the 1138 changes.

**Comment by digant73** [comment]
no #1138 is a current PR

**Comment by z00mantwo** [comment]
Okay. It's fixed by pulling your #1138 apparently that hasn't been rolled in to the "master".

Sorry for the fire drill.

**Comment by digant73** [comment]
good, however it's not my PR

**Comment by Zowen79** [comment]
The latest update has killed my TFT35_E3_V3_0. It updated like normal, but as soon as it finished updating the icons my screen went black and said: 
"Found outdated data:

Config: Update required
Insert the SD card with the required files and press the reset button to update."
I recompiled with some changes (changed to Classic Menu), it updated like it normal again, then right back to that same message. I restarted the whole machine, but still didn't work. Help

![20201006_145243](https://user-images.githubusercontent.com/66785162/95248501-6054af80-07e5-11eb-9f05-3575b503141e.jpg)

**Comment by z00mantwo** [comment]
Did you put the config.ini file on the SD? I've seen this myself and just put the config.ini on the SD then it went away. Config.ini had to match the updated firmware.

**Comment by Zowen79** [comment]
I will try that. Let you know in a few

**Comment by Zowen79** [comment]
That worked. Thanks a lot

**Comment by discip** [comment]
I think after the [latest commit](https://github.com/guruathwal/BIGTREETECH-TouchScreenFirmware/commit/462ded278c3f275fb0582d4b26dc0b131f4e87f7) this should be closed, because it is resolved.
