### ISSUE TITLE
BTT TFT35 E3 V3 26.X June 15, 2020 - Filament runout only works in marlin screen mode not TFT mode. 

### ISSUE THREAD

**Issue by telco55** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1617]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by telco55** [comment]
Reproduced several times. 
With the runout sensor installed and enabled in the Touch Screen mode will not allow a print to start. 
The mesage is "filament runout" and the print cancels and shuts down the temps.
Fortunately I am able to print in Marlin Mode just fine. 
I will have to use Marlin Mode till this is fixed. 
I need to tell everyone to not buy a BTT TFT screen till it this issue is resolved.
I have updated firmware on the SKR mini E3 V2 board several times with no effect.
   Please fix this issue so I can use the nice color screen. 
There several other issues with the screen like it hangs the screen in "Loading" after a print pause. This requires a print restart(power cycle). 
When switching back and forth between Marlin screen and TFT screen I found that the Probe Offset was not shared between screen modes. I am not sure if that is normal or a bug. I also had in a Marlin mode session during a print the that the screen became unresponsive  I was unable to get the screen menu to change.  
Thanks    Please Help

**Comment by oldman4U** [comment]
Please update to the most recent TFT firmware.

Then read previous made tickets related to your issues. 

For those issues you see on your system but you can not find a ticket for make a new ticket per issue. Include all relevant information incl which filament sensor you use and where it is connected.

This is a friendly reminder, that this repository is about the TFT firmware and not a user group.

Thank you

**Comment by scathappens** [comment]
I have the same issue, have had a ticket going for this, it was supposed to be fixed however i have updated the firmware on the TFT35 today to the 04/02/2021 release and it has not solved this issue 

when the filament sensor notices a runout (printing from SD) the head parks as it should, then when i press resume it does nothing....then after a pause of about 30-60 seconds it says heater timout, when i press reheat it the heater turns off.
if i hit stop print at this time i get a message saying 'busy processing, please wait'

so the runout sensor is still not functioning as it should in the latest firmware (dated 04/02/2021)

I get the exact same reaction when i use the pause feature aswel, the head parks but then it will not resume in the same manner described as above

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1538

**Comment by 3dfixer** [comment]
does the filament sensor work when in marlin mode?
where is it connected too? board or tft

**Comment by scathappens** [comment]
I havent tested in marlin mode tbh, it is connected to the TFT...as stated the sensor works but i can't resume the print after reloading the filament, and the pause feature also will not allow resume either

**Comment by oldman4U** [comment]
telco55 seems to be a nine day wonder and does not answer his own ticket.

For issues related to his topic please read all the existing tickets snd also the pinned verified bugs ticket.

Thank you

**Comment by OnBudgetServices** [comment]
Having the same issues. I've installed the BTT sensor on a custom printer, using the SKR 1.4 board and TFT35 V3 touch screen. The sensor seems to work in Marlin mode, but it always activates, no matter what I do. It does not show anything in graphical mode, no matter what settings I use.

Marlin 2.0.7.2
TFT V3.0.26.x

Any advice would be much appreciated, been battling this for three days now. I'm close to removing it and returning it. I don't really print unmonitored anyways. The only reason I got it was to use up close to empty spools of filament.

**Comment by npcizzy** [comment]
@OnBudgetServices I'm having the same exact issue. I've updated my screens (TFT35V2) firmware to the latest. Marlins "classic" mode works great but as soon as I switch over to TS/TFT mode... Nothing.

**Comment by OnBudgetServices** [comment]
@npcizzy I was able to get it not always to trigger. I changed  FIL_RUNOUT_STATE from low to high, and that solved that issue. Still no dice on the graphical interface, but it does work if you swap over to the Marlin simulator once it's detected a runout state. Not ideal, but at least there's a way to interact and fix it. I'm assuming this is a firmware issue at this point with the TFT35.

**Comment by oldman4U** [comment]
And when you print from touchscreen you made sure to have a M75 in the
start gCode of your slicer?

Mike Bowden <notifications@github.com> schrieb am Mi. 17. Feb. 2021 um
16:17:

**Comment by OnBudgetServices** [comment]
I didn't. I've got a long print running now, but I have a few smaller ones I can test this with after that.

How does adding a print timer help with the filament dialog for the GUI?

**Comment by oldman4U** [comment]
It helps in case you print from on board sd in touchscreen mode. Marlin
does not know about the print otherwise

Mike Bowden <notifications@github.com> schrieb am Mi. 17. Feb. 2021 um
16:59:

**Comment by OnBudgetServices** [comment]
Ah, got ya.

I'll give it a shot, thanks!

**Comment by Budis3** [comment]
In another bug report over this same bug I could solve it thanks a comment from a user. If you put in you start G-code M75 the sensor works but another bug appears.
For more details: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1634

**Comment by oldman4U** [comment]
This ticket is about the topic mentioned in the headline.

Check if you have HOST_PROMPT_Support enabled in Marlin.

Budis3 <notifications@github.com> schrieb am Fr. 19. Feb. 2021 um 18:46:

**Comment by oldman4U** [comment]
What is the status of the reported issue?

**Comment by Budis3** [comment]
I not consider it complete because if you apply this solution appears another bug. More detaills here:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1634
And another reason is, if the another not have a correct solution and here find another better then it should been open.

**Comment by digant73** [comment]
Try PR #1718 it could solve the problem

**Comment by oldman4U** [comment]
I have been testing filament runout for seversl hours using the TFT firmware from yesterday and it worked great. Sensor connected to TFT - printing from TFT storage it triggers correctly and purges at the pause position. @digant73 Please mention this ticket in your PR.

Thank you

**Comment by oldman4U** [comment]
@telco55

Please respond to your own ticket or I expect the reported issues to be solved.

Thank you
